Imports System.Windows.Forms
Imports PropertyInsuranceClaims.Common

''' <summary>
''' Claim-level summary report — printable claim summary with all details.
''' </summary>
Public Class frmClaimSummaryReport
    Inherits Form

    Private _claimID As Integer
    Private txtReport As New TextBox()
    Private WithEvents btnPrint As New Button()
    Private WithEvents btnExport As New Button()
    Private WithEvents btnClose As New Button()

    Public Sub New(claimID As Integer)
        _claimID = claimID
    End Sub

    Private Sub frmClaimSummaryReport_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.Text = "Claim Summary Report"
        Me.Size = New Drawing.Size(700, 550)
        Me.StartPosition = FormStartPosition.CenterParent
        InitializeControls()
        GenerateReport()
    End Sub

    Private Sub InitializeControls()
        txtReport.Dock = DockStyle.Fill : txtReport.Multiline = True : txtReport.ReadOnly = True
        txtReport.ScrollBars = ScrollBars.Vertical : txtReport.Font = New Drawing.Font("Consolas", 9)
        Me.Controls.Add(txtReport)

        Dim pnlBottom As New Panel() With {.Dock = DockStyle.Bottom, .Height = 40}
        btnPrint.Location = New Drawing.Point(10, 5) : btnPrint.Size = New Drawing.Size(80, 30) : btnPrint.Text = "&Print" : pnlBottom.Controls.Add(btnPrint)
        btnExport.Location = New Drawing.Point(100, 5) : btnExport.Size = New Drawing.Size(80, 30) : btnExport.Text = "&Export" : pnlBottom.Controls.Add(btnExport)
        btnClose.Location = New Drawing.Point(580, 5) : btnClose.Size = New Drawing.Size(80, 30) : btnClose.Text = "&Close" : pnlBottom.Controls.Add(btnClose)
        Me.Controls.Add(pnlBottom)
        txtReport.BringToFront()
    End Sub

    Private Sub GenerateReport()
        Dim sb As New Text.StringBuilder()
        sb.AppendLine("=" & New String("="c, 60))
        sb.AppendLine("           CLAIM SUMMARY REPORT")
        sb.AppendLine("=" & New String("="c, 60))
        sb.AppendLine()
        sb.AppendLine("Claim ID: " & _claimID.ToString())
        sb.AppendLine("Generated: " & DateTime.Now.ToString("MM/dd/yyyy HH:mm"))
        sb.AppendLine("Generated By: " & GlobalState.CurrentUser)
        sb.AppendLine()
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("CLAIM DETAILS")
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("(Claim details would be populated from database)")
        sb.AppendLine()
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("FINANCIAL SUMMARY")
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("(Reserves, payments, recoveries would show here)")
        sb.AppendLine()
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("ACTIVITY LOG")
        sb.AppendLine("-" & New String("-"c, 60))
        sb.AppendLine("(Recent activities would be listed here)")
        txtReport.Text = sb.ToString()
    End Sub

    Private Sub btnPrint_Click(sender As Object, e As EventArgs) Handles btnPrint.Click
        MessageBox.Show("Print dialog would open.", "Print", MessageBoxButtons.OK, MessageBoxIcon.Information)
    End Sub

    Private Sub btnExport_Click(sender As Object, e As EventArgs) Handles btnExport.Click
        Dim sfd As New SaveFileDialog() With {.Filter = "Text Files|*.txt|PDF|*.pdf", .FileName = "ClaimReport_" & _claimID.ToString() & ".txt"}
        If sfd.ShowDialog() = DialogResult.OK Then
            IO.File.WriteAllText(sfd.FileName, txtReport.Text)
            MessageBox.Show("Report exported.", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End If
    End Sub

    Private Sub btnClose_Click(sender As Object, e As EventArgs) Handles btnClose.Click
        Me.Close()
    End Sub
End Class
